<?php
return [
    /*
    |--------------------------------------------------------------------------
    | Application Environment
    |--------------------------------------------------------------------------
    |
    | Pesapal will utilize this option to determine which 
    | mode your App is running, either Sandbox or Live
    |
    | Local - Means your App is running on a Sandbox Mode.
    | Production - Means your App is running on a Live Mode
    |
    */
    'env' => env('APP_ENV', 'local'),
    /*
    |--------------------------------------------------------------------------
    | Authentication / Configuration
    |--------------------------------------------------------------------------
    | 
    | NOTE:
    | ---------
    | PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your 
    | developement and when you are ready to go live change to 
    | https://www.pesapal.com.
    |
    | WHAT TO DO:
    | ---------
    | Register a merchant account on https://demo.pesapal.com and use the 
    | 'merchant key' for testing.
    | 
    | Use the 'consumer secret' from your test account on 
    | https://demo.pesapal.com
    | 
    | Change 'iframelink' to //https://www.pesapal.com/API/PostPesapalDirectOrderV4 
    | when you are ready to go live! 
    | 
    | *** THIS PACKAGE WILL DO ABOVE FOR YOU, JUST CHANGE YOUR APP_ENV TO 
    | PRODUCTION OR LOCAL ***
    |
    | When you are ready to go live make sure you change the 'consumer key' 
    | & 'consumer secret' to the live account registered on https://pesapal.com
    |
    */
    'auth' => [
        'token_params' => NULL,
        'consumer_key' => env('PESAPAL_CONSUMER_KEY', ''),
        'consumer_secret' => env('PESAPAL_CONSUMER_SECRET', ''),
        'live_iframelink' => 'https://www.pesapal.com/API/PostPesapalDirectOrderV4',
        'demo_iframelink' => 'http://demo.pesapal.com/api/PostPesapalDirectOrderV4'
    ],
    /*
    |--------------------------------------------------------------------------
    | Define the callback_url
    |--------------------------------------------------------------------------
    |
    | This is the full url pointing to the page the iframe redirects to 
    | after processing the order on pesapal.com
    | 
    */
    'callback_url' => env('PESAPAL_CALLBACK_URL', 'http://test.com/payment-gateways-php/pesapal-php/'),
    /*
    |--------------------------------------------------------------------------
    | Field Names
    |--------------------------------------------------------------------------
    |
    | You may wish for to select prefered form details posted by your 
    | application to be used by pesapal.
    | 
    */
    'fields' => [
        'amount' => 'number_format(PESAPAL_FIELD_AMOUNT, 2)', //format amount to 2 decimal places
        'description' => 'PESAPAL_FIELD_DESC',
        'type' => 'MERCHANT', //default value = MERCHANT
        'reference' => 'PESAPAL_FIELD_REF', //unique order id of the transaction, generated by merchant
        'first_name' => 'PESAPAL_FIELD_FNAME',
        'last_name' => 'PESAPAL_FIELD_LNAME',
        'email' => 'PESAPAL_FIELD_EMAIL',
        'phonenumber' => 'PESAPAL_FIELD_PHONE' //ONE of email or phonenumber is required
    ]
];